### ISSUE TITLE
Error: Failed to lookup view "404" in views directory "./app/views"

### ISSUE THREAD

**Issue by kfogel** [hmis-tools/hmis-api-demo-client#26]
Some time shortly after startup, we consistently see this error happen a couple of times (this is still true at least as of commit a5a91df on master, right after the `14-export-clients` branch was merged in):

```
deploy@localhost:~/openhmis-intake$ node server.js 
--
OpenHMIS Intake application started
Environment:                    undefined
Port:                           3000
--
Error: Failed to lookup view "404" in views directory "./app/views"
    at EventEmitter.render (/home/deploy/openhmis-intake/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/home/deploy/openhmis-intake/node_modules/express/lib/response.js:961:7)
    at /home/deploy/openhmis-intake/config/express.js:68:21
    at Layer.handle [as handle_request] (/home/deploy/openhmis-intake/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:312:13)
    at /home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:330:12)
    at next (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/home/deploy/openhmis-intake/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:312:13)
Error: Failed to lookup view "404" in views directory "./app/views"
    at EventEmitter.render (/home/deploy/openhmis-intake/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/home/deploy/openhmis-intake/node_modules/express/lib/response.js:961:7)
    at /home/deploy/openhmis-intake/config/express.js:68:21
    at Layer.handle [as handle_request] (/home/deploy/openhmis-intake/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:312:13)
    at /home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:330:12)
    at next (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/home/deploy/openhmis-intake/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/deploy/openhmis-intake/node_modules/express/lib/router/index.js:312:13)
```

**Comment by cecilia-donnelly** [comment]
Yes!  It only happens the first time the app is started in a given browser tab.  If you look in the "Network" tab of the console, I believe that the 404 is being caused by the browser not finding a favicon image.

**Comment by bharti614** [comment]
> Yes! It only happens the first time the app is started in a given browser tab. If you look in the "Network" tab of the console, I believe that the 404 is being caused by the browser not finding a favicon image.

can you tell me when again it will start working
