### ISSUE TITLE
Node server crashes if it can't connect to HMIS server

### ISSUE THREAD

**Issue by cecilia-donnelly** [hmis-tools/hmis-api-demo-client#31]
If the Node JS server (for this client application) fails to connect to the HMIS server named in `local.js` then it will crash with error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

This specific error was generated with a local instance of HMIS (`localhost:8080`), but I've seen this happen with a remote server, too.

We should return an error to the user instead of crashing the client server.

**Comment by kfogel** [comment]
I recall that @slifty mentioned this to me as a known unhandled error, way back when.  So it's not unexpected -- demo-only code and all that.  Still, we should fix it, now that the client is getting more use.
